### PR TITLE
Add stun server for ip discovery and flag stun

### LINKED ISSUE #176: add stun for p2p network
The code can reference the project [erigon](https://github.com/erigontech/erigon/blob/main/p2p/nat/nat.go)
and the stun server can use the same as [trin](https://github.com/ethereum/trin/blob/master/portalnet/src/socket.rs)

### PR DESCRIPTION
**Pull request by r4f4ss**
fix #176 

new usage ([reference usage](https://erigon.gitbook.io/erigon/advanced-usage/options)):
```
$shisui --nat stun
```
or
```
$shisui --nat stun:<addr>
```

### CODE REVIEW

**Comment by GrapeBaBa** [comment]
@r4f4ss (nit) Could this feature have a test?

**Review by fearlessfe — COMMENTED** [review]
It just create a `STUN{}`, It should be a place to get the real IP and set to the localNode

**Comment by r4f4ss** [comment]
> It just create a `STUN{}`, It should be a place to get the real IP and set to the localNode

Can you elaborate more please? It is not clear what are the demands

**Comment by r4f4ss** [comment]
> It just create a `STUN{}`, It should be a place to get the real IP and set to the localNode

Added function main.doPortMapping that set address and port for localNode, reference implementation from: https://github.com/optimism-java/shisui/blob/ee38628954a7057bdedcc27043bb3cbca22af9f7/cmd/bootnode/main.go#L153

**Review by fearlessfe — APPROVED** [review]

**Pull request merged**
